version: "3.9"
services:

  anicat:
    image: wmoon/anicat:latest
    container_name: ab
    ports:
      - 9996:8080
    depends_on:
      - qb
    volumes:
      - ./cfg/env.yaml:/opt/env.yaml
      - ./bangumi:/bangumi
    restart: unless-stopped
 

  qb:
    image: superng6/qbittorrentee:latest
    container_name: qb
    ports:
      - 8989:8989 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUIPORT=8989 
    volumes:
      - ./qb:/config
      - ./bangumi:/bangumi
    restart: unless-stopped
    