

type P struct {
	TorrentContentLayout               string         `json:"torrent_content_layout"`
	StartPausedEnabled                 bool           `json:"start_paused_enabled"`
	TorrentStopCondition               string         `json:"torrent_stop_condition"`
	AutoDeleteMode                     bool           `json:"auto_delete_mode"`
	PreallocateAll                     bool           `json:"preallocate_all"`
	IncompleteFilesEXT                 bool           `json:"incomplete_files_ext"`
	AutoTmmEnabled                     string         `json:"auto_tmm_enabled"`
	TorrentChangedTmmEnabled           string         `json:"torrent_changed_tmm_enabled"`
	SavePathChangedTmmEnabled          string         `json:"save_path_changed_tmm_enabled"`
	CategoryChangedTmmEnabled          string         `json:"category_changed_tmm_enabled"`
	SavePath                           string         `json:"save_path"`
	TempPathEnabled                    bool           `json:"temp_path_enabled"`
	TempPath                           string         `json:"temp_path"`
	ExportDir                          string         `json:"export_dir"`
	ExportDirFin                       string         `json:"export_dir_fin"`
	ScanDirs                           map[string]int `json:"scan_dirs"`
	ExcludedFileNamesEnabled           bool           `json:"excluded_file_names_enabled"`
	ExcludedFileNames                  string         `json:"excluded_file_names"`
	MailNotificationEnabled            bool           `json:"mail_notification_enabled"`
	MailNotificationSender             string         `json:"mail_notification_sender"`
	MailNotificationEmail              string         `json:"mail_notification_email"`
	MailNotificationSMTP               string         `json:"mail_notification_smtp"`
	MailNotificationSSLEnabled         bool           `json:"mail_notification_ssl_enabled"`
	MailNotificationAuthEnabled        bool           `json:"mail_notification_auth_enabled"`
	MailNotificationUsername           string         `json:"mail_notification_username"`
	MailNotificationPassword           string         `json:"mail_notification_password"`
	AutorunOnTorrentAddedEnabled       bool           `json:"autorun_on_torrent_added_enabled"`
	AutorunOnTorrentAddedProgram       string         `json:"autorun_on_torrent_added_program"`
	AutorunEnabled                     bool           `json:"autorun_enabled"`
	AutorunProgram                     string         `json:"autorun_program"`
	ListenPort                         int            `json:"listen_port"`
	Upnp                               bool           `json:"upnp"`
	MaxConnec                          int            `json:"max_connec"`
	MaxConnecPerTorrent                int            `json:"max_connec_per_torrent"`
	MaxUploads                         int            `json:"max_uploads"`
	MaxUploadsPerTorrent               int            `json:"max_uploads_per_torrent"`
	ProxyType                          int            `json:"proxy_type"`
	ProxyAuthEnabled                   bool           `json:"proxy_auth_enabled"`
	ProxyIP                            string         `json:"proxy_ip"`
	ProxyPort                          int            `json:"proxy_port"`
	ProxyPeerConnections               bool           `json:"proxy_peer_connections"`
	ProxyTorrentsOnly                  bool           `json:"proxy_torrents_only"`
	ProxyHostnameLookup                bool           `json:"proxy_hostname_lookup"`
	ProxyUsername                      string         `json:"proxy_username"`
	ProxyPassword                      string         `json:"proxy_password"`
	IPFilterEnabled                    bool           `json:"ip_filter_enabled"`
	IPFilterPath                       string         `json:"ip_filter_path"`
	IPFilterTrackers                   bool           `json:"ip_filter_trackers"`
	BannedIPS                          string         `json:"banned_IPs"`
	UpLimit                            int            `json:"up_limit"`
	DLLimit                            int            `json:"dl_limit"`
	AltUpLimit                         int            `json:"alt_up_limit"`
	AltDLLimit                         int            `json:"alt_dl_limit"`
	BittorrentProtocol                 string         `json:"bittorrent_protocol"`
	LimitUTPRate                       bool           `json:"limit_utp_rate"`
	LimitTCPOverhead                   bool           `json:"limit_tcp_overhead"`
	LimitLANPeers                      bool           `json:"limit_lan_peers"`
	SchedulerEnabled                   bool           `json:"scheduler_enabled"`
	Dht                                bool           `json:"dht"`
	Pex                                bool           `json:"pex"`
	Lsd                                bool           `json:"lsd"`
	Encryption                         string         `json:"encryption"`
	AnonymousMode                      bool           `json:"anonymous_mode"`
	MaxActiveCheckingTorrents          string         `json:"max_active_checking_torrents"`
	QueueingEnabled                    bool           `json:"queueing_enabled"`
	MaxRatioEnabled                    bool           `json:"max_ratio_enabled"`
	MaxRatio                           int            `json:"max_ratio"`
	MaxSeedingTimeEnabled              bool           `json:"max_seeding_time_enabled"`
	MaxSeedingTime                     int            `json:"max_seeding_time"`
	MaxRatioAct                        int            `json:"max_ratio_act"`
	AddTrackersEnabled                 bool           `json:"add_trackers_enabled"`
	AddTrackers                        string         `json:"add_trackers"`
	RSSProcessingEnabled               bool           `json:"rss_processing_enabled"`
	RSSRefreshInterval                 string         `json:"rss_refresh_interval"`
	RSSMaxArticlesPerFeed              string         `json:"rss_max_articles_per_feed"`
	RSSAutoDownloadingEnabled          bool           `json:"rss_auto_downloading_enabled"`
	RSSDownloadRepackProperEpisodes    bool           `json:"rss_download_repack_proper_episodes"`
	RSSSmartEpisodeFilters             string         `json:"rss_smart_episode_filters"`
	Locale                             string         `json:"locale"`
	PerformanceWarning                 bool           `json:"performance_warning"`
	WebUIDomainList                    string         `json:"web_ui_domain_list"`
	WebUIAddress                       string         `json:"web_ui_address"`
	WebUIPort                          int            `json:"web_ui_port"`
	WebUIUpnp                          bool           `json:"web_ui_upnp"`
	UseHTTPS                           bool           `json:"use_https"`
	WebUIHTTPSCERTPath                 string         `json:"web_ui_https_cert_path"`
	WebUIHTTPSKeyPath                  string         `json:"web_ui_https_key_path"`
	WebUIUsername                      string         `json:"web_ui_username"`
	BypassLocalAuth                    bool           `json:"bypass_local_auth"`
	BypassAuthSubnetWhitelistEnabled   bool           `json:"bypass_auth_subnet_whitelist_enabled"`
	BypassAuthSubnetWhitelist          string         `json:"bypass_auth_subnet_whitelist"`
	WebUIMaxAuthFailCount              string         `json:"web_ui_max_auth_fail_count"`
	WebUIBanDuration                   string         `json:"web_ui_ban_duration"`
	WebUISessionTimeout                string         `json:"web_ui_session_timeout"`
	AlternativeWebuiEnabled            bool           `json:"alternative_webui_enabled"`
	AlternativeWebuiPath               string         `json:"alternative_webui_path"`
	WebUIClickjackingProtectionEnabled bool           `json:"web_ui_clickjacking_protection_enabled"`
	WebUICSRFProtectionEnabled         bool           `json:"web_ui_csrf_protection_enabled"`
	WebUISecureCookieEnabled           bool           `json:"web_ui_secure_cookie_enabled"`
	WebUIHostHeaderValidationEnabled   bool           `json:"web_ui_host_header_validation_enabled"`
	WebUIUseCustomHTTPHeadersEnabled   bool           `json:"web_ui_use_custom_http_headers_enabled"`
	WebUICustomHTTPHeaders             string         `json:"web_ui_custom_http_headers"`
	WebUIReverseProxyEnabled           bool           `json:"web_ui_reverse_proxy_enabled"`
	WebUIReverseProxiesList            string         `json:"web_ui_reverse_proxies_list"`
	DyndnsEnabled                      bool           `json:"dyndns_enabled"`
	DyndnsService                      string         `json:"dyndns_service"`
	DyndnsDomain                       string         `json:"dyndns_domain"`
	DyndnsUsername                     string         `json:"dyndns_username"`
	DyndnsPassword                     string         `json:"dyndns_password"`
	ResumeDataStorageType              string         `json:"resume_data_storage_type"`
	MemoryWorkingSetLimit              string         `json:"memory_working_set_limit"`
	CurrentNetworkInterface            string         `json:"current_network_interface"`
	CurrentInterfaceAddress            string         `json:"current_interface_address"`
	SaveResumeDataInterval             string         `json:"save_resume_data_interval"`
	RecheckCompletedTorrents           bool           `json:"recheck_completed_torrents"`
	RefreshInterval                    string         `json:"refresh_interval"`
	ResolvePeerCountries               bool           `json:"resolve_peer_countries"`
	ReannounceWhenAddressChanged       bool           `json:"reannounce_when_address_changed"`
	AsyncIoThreads                     string         `json:"async_io_threads"`
	HashingThreads                     string         `json:"hashing_threads"`
	FilePoolSize                       string         `json:"file_pool_size"`
	CheckingMemoryUse                  string         `json:"checking_memory_use"`
	DiskCache                          string         `json:"disk_cache"`
	DiskCacheTTL                       string         `json:"disk_cache_ttl"`
	DiskQueueSize                      int            `json:"disk_queue_size"`
	DiskIoType                         string         `json:"disk_io_type"`
	DiskIoReadMode                     string         `json:"disk_io_read_mode"`
	DiskIoWriteMode                    string         `json:"disk_io_write_mode"`
	EnableCoalesceReadWrite            bool           `json:"enable_coalesce_read_write"`
	EnablePieceExtentAffinity          bool           `json:"enable_piece_extent_affinity"`
	EnableUploadSuggestions            bool           `json:"enable_upload_suggestions"`
	SendBufferWatermark                string         `json:"send_buffer_watermark"`
	SendBufferLowWatermark             string         `json:"send_buffer_low_watermark"`
	SendBufferWatermarkFactor          string         `json:"send_buffer_watermark_factor"`
	ConnectionSpeed                    string         `json:"connection_speed"`
	SocketBacklogSize                  string         `json:"socket_backlog_size"`
	OutgoingPortsMin                   string         `json:"outgoing_ports_min"`
	OutgoingPortsMax                   string         `json:"outgoing_ports_max"`
	UpnpLeaseDuration                  string         `json:"upnp_lease_duration"`
	PeerTos                            string         `json:"peer_tos"`
	UTPTCPMixedMode                    string         `json:"utp_tcp_mixed_mode"`
	IdnSupportEnabled                  bool           `json:"idn_support_enabled"`
	EnableMultiConnectionsFromSameIP   bool           `json:"enable_multi_connections_from_same_ip"`
	ValidateHTTPSTrackerCertificate    bool           `json:"validate_https_tracker_certificate"`
	SsrfMitigation                     bool           `json:"ssrf_mitigation"`
	BlockPeersOnPrivilegedPorts        bool           `json:"block_peers_on_privileged_ports"`
	EnableEmbeddedTracker              bool           `json:"enable_embedded_tracker"`
	EmbeddedTrackerPort                string         `json:"embedded_tracker_port"`
	EmbeddedTrackerPortForwarding      bool           `json:"embedded_tracker_port_forwarding"`
	UploadSlotsBehavior                string         `json:"upload_slots_behavior"`
	UploadChokingAlgorithm             string         `json:"upload_choking_algorithm"`
	AnnounceToAllTrackers              bool           `json:"announce_to_all_trackers"`
	AnnounceToAllTiers                 bool           `json:"announce_to_all_tiers"`
	AnnounceIP                         string         `json:"announce_ip"`
	MaxConcurrentHTTPAnnounces         string         `json:"max_concurrent_http_announces"`
	StopTrackerTimeout                 string         `json:"stop_tracker_timeout"`
	PeerTurnover                       string         `json:"peer_turnover"`
	PeerTurnoverCutoff                 string         `json:"peer_turnover_cutoff"`
	PeerTurnoverInterval               string         `json:"peer_turnover_interval"`
	RequestQueueSize                   string         `json:"request_queue_size"`
}
