version: "3.9"
services:

  anicat:
    image: wmooon/anicat:latest
    container_name: anicat
    ports:
      - "12314:12314"
    environment:
      - DEBUG=false
    depends_on:
      - qb
    user: "1000:1000"
    volumes:
      - ./cfg/env.yaml:/opt/env.yaml
      - ./bangumi:/bangumi
    restart: unless-stopped
 

  qb:
    image: superng6/qbittorrentee:latest
    container_name: qb
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUIPORT=8080
    volumes:
      - ./qb:/config
      - ./bangumi:/bangumi
    restart: unless-stopped
    